[package]
name = "grenad"
description = "Tools to sort, merge, write, and read immutable key-value pairs."
version = "0.4.4"
authors = ["Kerollmops <clement@meilisearch.com>"]
repository = "https://github.com/meilisearch/grenad"
documentation = "https://docs.rs/grenad"
edition = "2018"
license = "MIT"

[dependencies]
bytemuck = { version = "1.13.0", features = ["derive"] }
byteorder = "1.4.3"
flate2 = { version = "1.0", optional = true }
lz4_flex = { version = "0.10.0", optional = true }
snap = { version = "1.1.0", optional = true }
tempfile = { version = "3.3.0", optional = true }
zstd = { version = "0.12.3", optional = true }

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }
quickcheck = "1.0"
rand = "0.8.5"
grenad-0-4 = { version = "0.4.1", package = "grenad" } # do not update, backward compatibility test

[[bench]]
name = "index-levels"
harness = false

[features]
default = ["tempfile", "snappy"]
snappy = ["snap"]
zlib = ["flate2"]
lz4 = ["lz4_flex"]
